// POSTS
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const CHANGE_CURRENT_POST = 'CHANGE_CURRENT_POST';


// Comments
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';

export const CREATE_COMMENTS_SUCCESS = 'CREATE_COMMENTS_SUCCESS';


// Categories
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
